### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by kyvaith**
Triggering systemd-update-done to prevent 20sec wait on LiveCD boot.

### CODE REVIEW

**Comment by lots0logs** [comment]
@kyvaith Could you provide more details as to why this is necessary, including any applicable reference links? Thanks in advance!

**Comment by karasu** [comment]
@lots0logs : Sorry if I was too hasty merging this.

**Comment by lots0logs** [comment]
@karasu No worries! Obviously the changes are harmless in this case :wink:

**Comment by kyvaith** [comment]
@lots0logs Hi! I've noticed in systemd-analize, that ldconfig is taking half of a time to boot LiveCD. Thesame situation in other distros, eg. Sabayon, Manjaro etc. This is bug, with was resloved in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1195998#c7 and now in Sabayon: https://github.com/mudler/docker-sabayon-spinbase-amd64/commit/09e77be65aacffd74d7d5897e07465413d10548d . It hapens, becouse LiveCD FS is never-booted system, so ldconfig had no chance to run.


image

**Comment by kyvaith** [comment]
BTW. I do not know the cycle of ISO image generation - when and where I can expect testbuild ISO with this change? :)

**Comment by lots0logs** [comment]
@kyvaith Thanks for the info, much appreciated! :smile:

**Comment by kyvaith** [comment]
Thanks! If you could just tell when I could pick up test ISO.

**Pull request merged**
